version: "3.7"

services:
  api:
    build:
      context: .
      target: dev
    #stdin_open: true
    #tty: true
    command: sheetManagerAPI start
    volumes:
      - ".:/usr/src/app"
    ports:
      - "8080:8080"
    environment:
      - SHEET_ID=your-google-sheet-token

