version: "3.7"

services:
  app:
    build:
      context: .
      target: dev
    command: sheetManagerAPI start
    volumes:
      - ".:/usr/src/app"
    ports:
      - "8080:8080"
    environment:
      - SHEET_ID=1LoDpDFIbpsESS0lZ0WUdezDOOHQDZRdsr0cWgvWry6g

